trigger:
  branches:
    include:
      - master  # Trigger the pipeline when changes are pushed to the main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  containerRegistry: 'budgetacr.azurecr.io'  # Azure Container Registry URL
  dockerImageName: 'budget-app'             # Docker image name

steps:
  # Clone the repository
  - task: Checkout@1  # Use Checkout@1, the correct version of the task

  # Build and Push Docker Image to ACR
  - script: |
      docker-compose build
      docker tag budget-app:latest $(containerRegistry)/$(dockerImageName):latest
    displayName: 'Build Docker Image'

  # Log in to Azure Container Registry (ACR)
  - script: |
      echo $(DOCKER_REGISTRY_PASSWORD) | docker login $(containerRegistry) -u $(DOCKER_REGISTRY_USERNAME) --password-stdin
    env:
      DOCKER_REGISTRY_USERNAME: "mybudgetacr"  # Set your Docker username
    displayName: 'Log in to Azure Container Registry'

  # Push the Docker image to ACR
  - script: |
      docker push $(containerRegistry)/$(dockerImageName):latest
    displayName: 'Push Docker Image to ACR'

  # Display Debug Information
  - script: |
      echo "ACR_USERNAME: $(DOCKER_REGISTRY_USERNAME)"
      echo "ACR_PASSWORD: $(DOCKER_REGISTRY_PASSWORD)"
      echo "containerRegistry: $(containerRegistry)"
    displayName: 'Display Debug Information'

  # Deploy to Azure App Service
  - task: AzureWebAppContainer@1
    inputs:
      azureSubscription: 'Microsoft Azure Sponsorship(c857a1ea-6e95-466f-806b-e3e7a7489c87)'  # Azure service connection name
      appName: 'budget-app'
      containers: '$(containerRegistry)/$(dockerImageName):latest'
